/* SPDX-License-Identifier: MIT
 *
 * taxi_mac_hw.h - hardware map of the ethernet-fmc-taxi-eth block design
 *
 * Copyright (c) 2026 Opsero Electronic Design Inc.
 *
 * One Taxi RGMII MAC (module reference taxi_rgmii_mac_N) and one AXI DMA
 * (axi_dma_N) per Ethernet FMC port.
 *
 * Where the addresses come from
 * -----------------------------
 * The AXI DMA instances have a Xilinx driver, so the SDT flow emits XPAR_
 * macros for them and those always win (the macro name differs between
 * flows/architectures, hence the XPAR_AXI_DMA_N / XPAR_XAXIDMA_N pair).
 * The taxi_rgmii_mac_N cells are module references -- generic PL nodes with
 * no driver -- so the SDT flow emits nothing for them and the addresses have
 * to be carried here. They are the ones assigned by assign_bd_address() in
 * Vivado/src/bd/bd_<family>.tcl, and they differ per board, so they are
 * selected from board.h (BOARD_<NAME>, generated by Vitis/py/build-vitis.py).
 *
 * ==> To add a board: add a "#elif defined(BOARD_<NAME>)" block below with
 *     that target's MAC and DMA bases. Read them from its address map: unzip
 *     Vivado/<target>/taxieth_wrapper.xsa and look at the ADDRESS entries for
 *     taxi_rgmii_mac_0..3 and axi_dma_0..3 in taxieth.hwh (the block design
 *     script pins them, so they are stable across builds).
 *
 * The DMA interrupt ids are not needed here: XAxiDma_LookupConfig() returns
 * them in XAxiDma_Config.IntrId[] (0 = MM2S/TX, 1 = S2MM/RX).
 */
#ifndef TAXI_MAC_HW_H
#define TAXI_MAC_HW_H

#include "xparameters.h"
#include "board.h"

#define TAXI_ETH_NUM_PORTS 4

/* ========================================================================
 * Per-board fallback address map
 *
 * Used for whichever bases xparameters.h does not define. Every board needs
 * a MAC stride and a DMA stride because the four instances are placed
 * contiguously by the block design script.
 * ==================================================================== */
#if defined(BOARD_ZCU104)
/* ZCU104 - ZynqMP, bd_zynqmp.tcl: the PL aperture starts at 0xA000_0000 */
#define TAXI_MAC_BASE_0       0xA0000000UL
#define TAXI_MAC_STRIDE       0x00001000UL   /* 4 KB per MAC */
#define TAXI_DMA_BASE_0       0xA0010000UL
#define TAXI_DMA_STRIDE       0x00010000UL   /* 64 KB per AXI DMA */

#elif defined(BOARD_KCU105)
/* KCU105 - MicroBlaze, bd_mb-us.tcl, which pins these segments explicitly
 * (see its "Address map" section) so they do not move between builds.
 * These four defines are the ONE place the KCU105 map lives. */
#define TAXI_MAC_BASE_0       0x40000000UL
#define TAXI_MAC_STRIDE       0x00001000UL   /* 4 KB per MAC */
#define TAXI_DMA_BASE_0       0x41E00000UL
#define TAXI_DMA_STRIDE       0x00010000UL   /* 64 KB per AXI DMA */

#else
#error "taxi_mac_hw.h: no address map for this board -- add a BOARD_<NAME> block"
#endif

#define TAXI_MAC_FALLBACK(n)  (TAXI_MAC_BASE_0 + (n) * TAXI_MAC_STRIDE)
#define TAXI_DMA_FALLBACK(n)  (TAXI_DMA_BASE_0 + (n) * TAXI_DMA_STRIDE)

/* ---- Taxi RGMII MAC register bases -------------------------------------
 * XPAR wins when the tools emit one (they do not today for a module
 * reference), otherwise the per-board map above. */
#ifdef XPAR_TAXI_RGMII_MAC_0_BASEADDR
#define TAXI_MAC_0_BASEADDR XPAR_TAXI_RGMII_MAC_0_BASEADDR
#else
#define TAXI_MAC_0_BASEADDR TAXI_MAC_FALLBACK(0)
#endif
#ifdef XPAR_TAXI_RGMII_MAC_1_BASEADDR
#define TAXI_MAC_1_BASEADDR XPAR_TAXI_RGMII_MAC_1_BASEADDR
#else
#define TAXI_MAC_1_BASEADDR TAXI_MAC_FALLBACK(1)
#endif
#ifdef XPAR_TAXI_RGMII_MAC_2_BASEADDR
#define TAXI_MAC_2_BASEADDR XPAR_TAXI_RGMII_MAC_2_BASEADDR
#else
#define TAXI_MAC_2_BASEADDR TAXI_MAC_FALLBACK(2)
#endif
#ifdef XPAR_TAXI_RGMII_MAC_3_BASEADDR
#define TAXI_MAC_3_BASEADDR XPAR_TAXI_RGMII_MAC_3_BASEADDR
#else
#define TAXI_MAC_3_BASEADDR TAXI_MAC_FALLBACK(3)
#endif

/* ---- AXI DMA register bases (used with XAxiDma_LookupConfig) ------------ */
#if defined(XPAR_AXI_DMA_0_BASEADDR)
#define TAXI_DMA_0_BASEADDR XPAR_AXI_DMA_0_BASEADDR
#elif defined(XPAR_XAXIDMA_0_BASEADDR)
#define TAXI_DMA_0_BASEADDR XPAR_XAXIDMA_0_BASEADDR
#else
#define TAXI_DMA_0_BASEADDR TAXI_DMA_FALLBACK(0)
#endif
#if defined(XPAR_AXI_DMA_1_BASEADDR)
#define TAXI_DMA_1_BASEADDR XPAR_AXI_DMA_1_BASEADDR
#elif defined(XPAR_XAXIDMA_1_BASEADDR)
#define TAXI_DMA_1_BASEADDR XPAR_XAXIDMA_1_BASEADDR
#else
#define TAXI_DMA_1_BASEADDR TAXI_DMA_FALLBACK(1)
#endif
#if defined(XPAR_AXI_DMA_2_BASEADDR)
#define TAXI_DMA_2_BASEADDR XPAR_AXI_DMA_2_BASEADDR
#elif defined(XPAR_XAXIDMA_2_BASEADDR)
#define TAXI_DMA_2_BASEADDR XPAR_XAXIDMA_2_BASEADDR
#else
#define TAXI_DMA_2_BASEADDR TAXI_DMA_FALLBACK(2)
#endif
#if defined(XPAR_AXI_DMA_3_BASEADDR)
#define TAXI_DMA_3_BASEADDR XPAR_AXI_DMA_3_BASEADDR
#elif defined(XPAR_XAXIDMA_3_BASEADDR)
#define TAXI_DMA_3_BASEADDR XPAR_XAXIDMA_3_BASEADDR
#else
#define TAXI_DMA_3_BASEADDR TAXI_DMA_FALLBACK(3)
#endif

/* Marvell 88E1510 PHY, MDIO address 0 on every port's own MDIO bus */
#define TAXI_ETH_PHY_ADDR 0

#endif /* TAXI_MAC_HW_H */
